### ISSUE TITLE
don't parse PE in reset vector

### ISSUE THREAD

**Issue by jyao1** [jyao1/rust-td#31]
we can use tool to parse the rust-shim PE file and fill the entrypoint to reset vector.

The tool is https://github.com/jyao1/rust-td/blob/master/rust-td-tool

The original code to search for PE entry is https://github.com/jyao1/rust-td/blob/master/rust-tdshim/ResetVector/Ia32/SearchForSecEntry.asm, Flat32SearchForSecEntryPoint().

REF: PE/COFF spec - https://docs.microsoft.com/en-us/windows/win32/debug/pe-format

**Comment by xiaoyuxlu** [comment]
ref: https://github.com/jyao1/rust-firmware/tree/master/rust-ipl/ResetVector
ref: https://github.com/jyao1/rust-firmware/tree/master/rust-firmware-tool

**Comment by haowqs** [comment]
done
